In [17]:
import pandas as pd

melb_data=pd.read_csv('data/melb_data.csv', sep=',')
mask=melb_data['Price'] > 2000000 # классический фильтр через 'маску' по цене
display(melb_data[mask].head()) # первые пять строк отфильтрованной таблицы. После фильтрации возвращается новый DataFrame, полученный из исходного, при этом исходная таблица melb_data остаётся без изменений
melb_data[melb_data['Price'] > 2000000] # не обязательно заносить маску в отдельную переменную — можно сразу вставлять условие в операцию индексации
melb_data[melb_data['Rooms'] == 3].shape[0] # Найдём количество зданий с тремя комнатами. Для этого отфильтруем таблицу по условию: обратимся к результирующей таблице по столбцу Rooms и найдём число строк в ней с помощью атрибута shape 
melb_data[(melb_data['Rooms'] == 3) & (melb_data['Price'] < 300000)].shape[0] # найдём число трёхкомнатных домов с ценой менее 300 тысяч
melb_data[((melb_data['Rooms'] == 3) | (melb_data['BuildingArea'] > 100)) & (melb_data['Price'] < 300000)].shape[0] # найдем дома с ценой менее 300 тысяч, у которых либо число комнат равно 3 либо площадь домов более 100 квадратных метров
melb_data[melb_data['Type'] == 't']['Rooms'].max() # нашли максимальное кол-во комнат в таунхаусах. Так как в результате фильтрации получается DataFrame, то обратимся к нему по столбцу Rooms и найдём максимальное значение

# более сложный трюк: найдём медианную площадь здания у объектов, чья цена выше средней. Для того чтобы оградить наш код от нагромождений, предварительно создадим переменную со средней ценой:
mean_price=melb_data['Price'].mean() # находим среднее значение по цене
melb_data[melb_data['Price'] > mean_price]['BuildingArea'].median() # найдём медианную площадь здания у объектов, чья цена выше средней(в тетради разложил сигнатуру данного мува)

#практика:
melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64') # изменил тип данных в признаке ванные комнаты с float на int
mask=melb_data['Bathroom'] < 1 # добавил маску по зданиям без ванных комнат 
display(melb_data[mask]) # вывод результата(34 шт)

melb_data[(melb_data['SellerG'] == 'Nelson') & (melb_data['Price'] > 3000000)].shape[0] # вывел на экран сколько в сете объектов, которые продали через Nelson, цена которых выше 3КК

melb_data[(melb_data['BuildingArea'] == 0)].min() # минимальная цена объекта, площадь здания которого равна 0(здание не строилось)

#вот тут по-интереснее=) Какова средняя цена объектов недвижимости в таблице melb_data с ценой менее одного миллиона, в которых либо количество комнат больше пяти, либо здание моложе 2015 года?
melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64') # изменил тип данных в признаке год постройки с float на int
melb_data[(melb_data['Price'] < 1000000) & ((melb_data['Rooms'] > 5) | (melb_data['YearBuilt'] > 2015))]['Price'].mean() # вот тут я обосрался - чтобы вывести по признаку цена среднее значение, забыл указать перед mean ['Price']

# В каком районе Мельбурна чаще всего продаются виллы и коттеджи (тип здания — h) с ценой меньше трёх миллионов?
melb_data[((melb_data['Price'] < 3000000) & (melb_data['Type'] == 'h'))]['Regionname'].mode()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
80,80,Albert Park,112 Beaconsfield Pde,3,h,2850000.0,PI,Buxton,4/03/2017,3.3,...,0.0,211.0,198.0,1890.0,Port Phillip,-37.8481,144.9499,Southern Metropolitan,3280.0,"-37.8481, 144.9499"
85,85,Albert Park,104 Richardson St,4,h,2300000.0,S,Marshall,7/05/2016,3.3,...,1.0,153.0,180.0,1880.0,Port Phillip,-37.8447,144.9523,Southern Metropolitan,3280.0,"-37.8447, 144.9523"
88,88,Albert Park,29 Faussett St,2,h,2120000.0,S,Greg,10/09/2016,3.3,...,1.0,199.0,107.0,1900.0,Port Phillip,-37.8422,144.9554,Southern Metropolitan,3280.0,"-37.8422, 144.9554"
92,92,Albert Park,2 Dundas Pl,3,h,2615000.0,S,Cayzer,10/12/2016,3.3,...,1.0,177.0,181.0,1880.0,Port Phillip,-37.8415,144.9585,Southern Metropolitan,3280.0,"-37.8415, 144.9585"
93,93,Albert Park,23 Finlay St,5,h,2100000.0,S,Greg,10/12/2016,3.3,...,1.0,237.0,126.0,1970.0,Port Phillip,-37.8436,144.9557,Southern Metropolitan,3280.0,"-37.8436, 144.9557"

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
139,139,Alphington,6 Naroon Rd,3,h,1485000.0,SP,McGrath,28/08/2016,6.4,...,0.0,597.0,126.0,1970.0,Darebin,-37.77810,145.02840,Northern Metropolitan,2211.0,"-37.7781, 145.0284"
281,281,Armadale,3/50 Denbigh Rd,2,u,546000.0,SP,hockingstuart,30/07/2016,6.3,...,0.0,0.0,126.0,1970.0,Stonnington,-37.85680,145.01610,Southern Metropolitan,4836.0,"-37.8568, 145.0161"
505,505,Balaclava,5/11 Albion St,2,u,497500.0,PI,hockingstuart,28/08/2016,6.6,...,0.0,0.0,126.0,1970.0,Port Phillip,-37.87390,144.99290,Southern Metropolitan,2952.0,"-37.8739, 144.9929"
584,584,Balwyn,5 Shrimpton Ct,2,h,1010000.0,PI,Marshall,30/07/2016,9.7,...,0.0,1611.0,126.0,1970.0,Boroondara,-37.80920,145.10160,Southern Metropolitan,5682.0,"-37.8092, 145.1016"
913,913,Bentleigh East,579 Warrigal Rd,3,h,700000.0,S,Thomson,22/05/2016,13.9,...,0.0,456.0,126.0,1970.0,Glen Eira,-37.93140,145.08080,Southern Metropolitan,10969.0,"-37.9314, 145.0808"
1063,1063,Brighton,17 New St,3,h,1900000.0,S,Marshall,6/08/2016,11.2,...,0.0,0.0,126.0,1970.0,Bayside,-37.93010,144.99350,Southern Metropolitan,10579.0,"-37.9301, 144.9935"
1070,1070,Brighton,1/5 Webb St,3,t,1067000.0,S,Kay,7/05/2016,11.2,...,1.0,0.0,126.0,1970.0,Bayside,-37.91190,144.98710,Southern Metropolitan,10579.0,"-37.9119, 144.9871"
1593,1593,Camberwell,5 Nicholsdale Rd,4,h,1400000.0,PI,Jellis,16/04/2016,7.8,...,0.0,693.0,126.0,1935.0,Boroondara,-37.83600,145.09140,Southern Metropolitan,8920.0,"-37.836, 145.0914"
2253,2253,Elsternwick,5/29 Nepean Hwy,2,u,410000.0,VB,Gary,28/05/2016,8.5,...,0.0,0.0,126.0,1970.0,Glen Eira,-37.88630,144.99960,Southern Metropolitan,4898.0,"-37.8863, 144.9996"
2777,2777,Glen Iris,25 Hope St,2,h,845000.0,S,Noel,10/09/2016,9.2,...,0.0,207.0,126.0,1970.0,Stonnington,-37.86300,145.05010,Southern Metropolitan,10412.0,"-37.863, 145.0501"
2797,2797,Glen Iris,130 High St,4,h,1550000.0,PI,Jellis,14/05/2016,9.2,...,0.0,769.0,126.0,1970.0,Boroondara,-37.86280,145.07340,Southern Metropolitan,10412.0,"-37.8628, 145.0734"
2808,2808,Glen Iris,1/64 Edgar St N,2,u,545000.0,S,Fletchers,16/07/2016,9.2,...,0.0,0.0,126.0,1970.0,Stonnington,-37.85000,145.04650,Southern Metropolitan,10412.0,"-37.85, 145.0465"
3390,3390,Ivanhoe,5/125 Locksley Rd,2,u,460000.0,VB,Fletchers,16/04/2016,7.9,...,0.0,0.0,126.0,1970.0,Banyule,-37.76620,145.05160,Eastern Metropolitan,5549.0,"-37.7662, 145.0516"
3556,3556,Kensington,7/51 Epsom Rd,2,u,526000.0,S,Nelson,22/08/2016,4.2,...,0.0,0.0,126.0,1970.0,Melbourne,-37.79190,144.92530,Northern Metropolitan,5263.0,"-37.7919, 144.9253"
3787,3787,Malvern,42 Cressy St,2,h,780000.0,VB,Jellis,14/05/2016,7.4,...,0.0,0.0,126.0,1970.0,Stonnington,-37.85020,145.04180,Southern Metropolitan,4675.0,"-37.8502, 145.0418"
4880,4880,Preston,19 Malpas St,4,h,1004000.0,S,Nelson,3/09/2016,8.8,...,0.0,650.0,126.0,1970.0,Darebin,-37.73460,145.02260,Northern Metropolitan,14577.0,"-37.7346, 145.0226"
5535,5535,South Melbourne,3 Park Pl,1,u,760500.0,S,Marshall,4/06/2016,2.1,...,0.0,438.0,126.0,1970.0,Port Phillip,-37.83530,144.96000,Southern Metropolitan,5943.0,"-37.8353, 144.96"
5642,5642,South Yarra,82/390 Toorak Rd,3,u,1072000.0,S,Kay,13/08/2016,3.3,...,0.0,0.0,126.0,1970.0,Stonnington,-37.84070,145.00430,Southern Metropolitan,14887.0,"-37.8407, 145.0043"
5711,5711,South Yarra,2/28 Tivoli Pl,2,u,910000.0,S,Williams,28/08/2016,3.3,...,0.0,0.0,126.0,1970.0,Melbourne,-37.83570,144.98590,Southern Metropolitan,14887.0,"-37.8357, 144.9859"
6392,6392,Toorak,1/183 Kooyong Rd,2,u,857000.0,S,Walsh,22/08/2016,4.6,...,0.0,0.0,126.0,1970.0,Stonnington,-37.84580,145.02210,Southern Metropolitan,7217.0,"-37.8458, 145.0221"
6406,6406,Toorak,6/183 Kooyong Rd,2,u,866000.0,S,Marshall,30/07/2016,4.6,...,0.0,0.0,126.0,1970.0,Stonnington,-37.84580,145.02210,Southern Metropolitan,7217.0,"-37.8458, 145.0221"
6651,6651,Yarraville,1/53 Stephen St,2,u,410000.0,PI,hockingstuart,6/08/2016,7.0,...,0.0,0.0,126.0,1970.0,Maribyrnong,-37.81290,144.89520,Western Metropolitan,6543.0,"-37.8129, 144.8952"
6671,6671,Yarraville,1a Kingston St,2,h,610000.0,SP,Jas,15/10/2016,7.0,...,0.0,94.0,126.0,1970.0,Maribyrnong,-37.81500,144.88270,Western Metropolitan,6543.0,"-37.815, 144.8827"
6856,6856,East Melbourne,37/22 Agnes St,2,u,740000.0,SP,Woodards,8/10/2016,1.5,...,0.0,0.0,126.0,1970.0,Melbourne,-37.81770,144.98010,Northern Metropolitan,3040.0,"-37.8177, 144.9801"
6866,6866,East Melbourne,9/35 Powlett St,2,u,872000.0,S,Dingle,28/05/2016,1.5,...,0.0,0.0,126.0,1970.0,Melbourne,-37.81540,144.98510,Northern Metropolitan,3040.0,"-37.8154, 144.9851"
6938,6938,Fawkner,1/66 Lorne St,3,u,470000.0,SP,Brad,26/07/2016,12.4,...,0.0,261.0,126.0,1970.0,Moreland,-37.71580,144.97220,Northern Metropolitan,5070.0,"-37.7158, 144.9722"
7494,7494,Balwyn North,215 Doncaster Rd,3,h,1670000.0,S,hockingstuart,29/04/2017,9.2,...,0.0,818.0,126.0,1970.0,Boroondara,-37.79390,145.08660,Southern Metropolitan,7809.0,"-37.7939, 145.0866"
8010,8010,Ivanhoe,1/53 Norman St,3,t,1060000.0,S,Purplebricks,29/04/2017,7.9,...,0.0,219.0,126.0,1980.0,Banyule,-37.76790,145.04660,Eastern Metropolitan,5549.0,"-37.7679, 145.0466"
8271,8271,Preston,86 Malpas St,3,h,1010000.0,SP,McGrath,20/05/2017,8.8,...,0.0,533.0,126.0,1970.0,Darebin,-37.73360,145.01680,Northern Metropolitan,14577.0,"-37.7336, 145.0168"
9090,9090,Caulfield East,5/33 Grange Rd,2,u,350000.0,SP,Gary,3/06/2017,8.4,...,0.0,0.0,126.0,1970.0,Glen Eira,-37.88385,145.04785,Southern Metropolitan,608.0,"-37.88385, 145.04785"
9917,9917,Hawthorn,1/30 Lisson Gr,2,h,1480000.0,S,Marshall,24/06/2017,5.3,...,0.0,241.0,126.0,1970.0,Boroondara,-37.82679,145.03021,Southern Metropolitan,11308.0,"-37.82679, 145.03021"
10795,10795,Preston,24 Mitchell St,3,h,1150000.0,SP,McGrath,8/07/2017,8.4,...,0.0,502.0,126.0,1970.0,Darebin,-37.74936,144.98949,Northern Metropolitan,14577.0,"-37.74936, 144.98949"
10895,10895,Balaclava,9/36 The Avenue,2,u,700000.0,SP,Marshall,12/08/2017,6.4,...,0.0,0.0,126.0,1970.0,Port Phillip,-37.87149,144.99746,Southern Metropolitan,2952.0,"-37.87149, 144.99746"
11204,11204,St Albans,148 Power St,3,h,702000.0,SP,Sweeney,12/08/2017,14.0,...,0.0,600.0,126.0,1970.0,Brimbank,-37.72945,144.79592,Western Metropolitan,14042.0,"-37.72945, 144.79592"

C:\Users\User\AppData\Local\Temp\ipykernel_10944\3131495405.py:23: FutureWarning: The default value of numeric_only in DataFrame.min is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  melb_data[(melb_data['BuildingArea'] == 0)].min() # минимальная цена объекта, площадь здания которого равна 0(здание не строилось)

0    Northern Metropolitan
Name: Regionname, dtype: object